# Copyright 2020, 2021, 2022 Clément "carlodrift" Raynaud and contributors
#
# This file is part of Altinspector.
#
# Altinspector is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Altinspector is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Altinspector.  If not, see <https://www.gnu.org/licenses/>.

name: Altinspector
version: ${project.version}
main: net.clementraynaud.altinspector.Altinspector
api-version: 1.13
authors: [ carlodrift ]
description: Find your players' other accounts beyond IP check
website: ${project.url}

commands:
  altinspector:
    description: The command to use Altinspector.
    usage: /altinspector
    permission: altinspector

permissions:
  altinspector:
    description: The permission to use Altinspector.
    default: op
